### ISSUE TITLE
Add an appropriate repository LICENSE

### ISSUE THREAD

**Issue by nballenger** [ruralinnovation/multi-svc-cartodb#10]
We need some form of license. For the moment I am going to use the BSD-3 license, but we should discuss whether that's appropriate to our needs.

**Comment by nballenger** [comment]
I've added a LICENSE.md file for BSD-3 in ec558fa.

**Comment by alex-cori** [comment]
I will talk with Vin about this one

**Comment by nballenger** [comment]
Per our offline discussions, it seems like we're good sticking with the current BSD-3 license, so I'm closing this issue.
