### ISSUE TITLE
Map edits in Builder not persisting

### ISSUE THREAD

**Issue by nballenger** [ruralinnovation/multi-svc-cartodb#14]
Currently you can upload a dataset, make a map based on it, publish that map, and view the published map. However, when you make changes to the map in the Builder edit interface, those changes do not appear to be persisted to any datastore, as they disappear on reload or if you change away from the edit interface.

**Comment by robert-claypool** [comment]
I have a working multi-container implementation of CartoDB using Docker Compose. It took weeks to figure out, and still I have a long list of technical debts to address, but I documented a lot along the way. Ping me on https://keybase.io/robert_claypool or email robert.claypool@fielda.com if you want to see.

**Comment by nballenger** [comment]
Thanks, @robert-claypool -- I sent you a Keybase message.

**Comment by nballenger** [comment]
This turned out to be a problem with the domain name not being set in app_config.yml's `vizjson_cache_domains` list, so some of the Redis visualization metadata wasn't getting invalidated correctly.
