### ISSUE TITLE
make use-build throws an error when using a different domain 

### ISSUE THREAD

**Issue by sindile** [ruralinnovation/multi-svc-cartodb#50]
When using a different domain other than osscarto-multi.localhost - make use-build throws an error.
Adding local SSL root authority cert to docker contexts:
    docker/varnish/ssl/osscarto-multiCA.pem
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/osscarto-multiCA.pem': No such file or directory
    docker/redis/ssl/osscarto-multiCA.pem
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/osscarto-multiCA.pem': No such file or directory
    docker/sqlapi/ssl/osscarto-multiCA.pem
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/osscarto-multiCA.pem': No such file or directory
    docker/windshaft/ssl/osscarto-multiCA.pem
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/osscarto-multiCA.pem': No such file or directory
    docker/cartodb/ssl/osscarto-multiCA.pem
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/osscarto-multiCA.pem': No such file or directory
    docker/nginx/ssl/osscarto-multiCA.pem
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/osscarto-multiCA.pem': No such file or directory

Adding certificate files to the Nginx docker context
cp: cannot stat '/home/hostw/multi-svc-cartodb/local-ssl/*.localhost.*': No such file or directory
Makefile:95: recipe for target 'use-build' failed
make: *** [use-build] Error 1

This is because the domain certificate information is hard coded in lines 108, 109 and 114 of https://github.com/ruralinnovation/multi-svc-cartodb/blob/master/bin/configure-repo-for-named-build.sh
Not sure where

**Comment by nballenger** [comment]
Thanks! Very helpful to have these reports, I really appreciate it.

**Comment by sindile** [comment]
Great
This is also hard coded in the various docker files:
docker/cartodb/Dockerfile line 39
docker/nginx/Dockerfile line 7,8,12
docker/redis/Dockerfile line 12
docker/sqlapi/Dockerfile line 27
docker/varnish/Dockerfile line 39
docker/windshaft/Dockerfile line 24

**Comment by nballenger** [comment]
@sindile - Can you paste me a copy of the build configuration json you used that produced errors? Thanks.

**Comment by sindile** [comment]
@nballenger 
{
    "carto_env": "development",

    "stack_scheme": "https",
    "stack_fqdn": "app.singleview.co.za",
    "stack_domain": "singleview.co.za",
    "stack_listen_port": "443",

    "user_db_basename": "cartodb_dev_user",
    "db_user_basename": "development_cartodb_user",
    "publicuser_role_name": "publicuser",
    "publicuser_role_password": "public",

    "sqlapi_host": "sqlapi",
    "sqlapi_listen_port": "8080",

    "postgis_host": "postgis",
    "postgis_listen_port": "5432",
    "postgis_batch_port": "5432",
    "postgis_admin_user": "postgres",

    "geocoder_db_name": "dataservices_db",
    "geocoder_pg_role_name": "geocoder_api",

    "redis_host": "redis",
    "redis_listen_port": "6379",

    "cartodb_scheme": "http",
    "cartodb_host": "cartodb",
    "cartodb_listen_port": "3000",
    "cartodb_secret_token": "d53d09d73dbe4b878f311d4cd89d0728",
    "cartodb_common_data_scheme": "https",
    "cartodb_common_data_username": "common-data",
    "cartodb_common_data_baseurl": "https://common-data.carto.com",
    "cartodb_common_data_regen_time": "86400",

"varnish_purge_hosts": [
        { "host": "localhost" },
        { "host": "127.0.0.1" },
        { "host": "postgis" },
        { "host": "redis" },
        { "host": "sqlapi" },
        { "host": "windshaft" },
        { "host": "cartodb" }
    ],
    "varnish_scheme": "http",
    "varnish_host": "varnish",
    "varnish_http_port": "6081",
    "varnish_telnet_port": "6082",

    "windshaft_scheme": "http",
    "windshaft_listen_port": "8181",
    "windshaft_host": "windshaft",

    "pgext_version": "0.28.1",
    "crankshaft_version": "0.8.2",
    "sqlapi_version": "3.0.0",
    "windshaft_version": "7.1.0",
    "cartodb_version": "v4.29.0",
    "dataservices_version": "0.0.2",
    "dataservices_api_server_version": "0.35.1-server",
    "dataservices_api_client_version": "0.26.2-client",
    "observatory_version": "1.9.0",
    "odbc_fdw_version": "0.3.0",

    "user_account_user_name": "dev",
    "user_account_password": "pass1234",
    "user_admin_password": "pass1234",
    "user_account_email": "cartouser@singleview.co.za",

    "org_account_org_name": "dev-org",
    "org_account_user_name": "admin4example",
    "org_account_email": "cartoorguser@singleview.co.za",
    "org_account_password": "pass1234"
}

**Comment by nballenger** [comment]
I just pushed a change in 34cb8f8584550263b1a9127b6450f555ef70561e that hard codes the name of the SSL files. You can still give any domain/subdomain you want to the generator script, but the filenames will be the same no matter what. The certificate will still show as valid for the given domain, but the certfiles that get copied into the Docker contexts will now be consistent.

The only reason this could be a problem is if you need to keep multiple sets of local TLS certs around in the same repository. I'm going to say that's a level of complexity I'm not prepared to support, unless somebody demonstrates a really compelling use case.

**Comment by sindile** [comment]
Thanks at @nballenger
